<!DOCTYPE html>
<html>
<head>
	<title>chatBox</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
<form id="form-creation" data-mode="creation">
    <p id="error">Cette discussion existe déja.</p>
   	<h2><i class="fas fa-lock"></i>Créer une discussion</h2>
	<input type="text" name="discussion" id="discussion"><br>
	<button type="submit" >Créer</button><br>
	<a href="php/join.php">Rejoindre une discussion</a>
</form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="js/main.js"></script>
</body>
</html>

