<!DOCTYPE html>
<html>
<head>
	<title>chatBox</title>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="message.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
    <div id="wrapper">
    <div id="menu">
        <p class="welcome">Welcome, <b></b></p>
        <p class="logout"><a id="exit" href="#">Exit Chat</a></p>
        <div style="clear:both"></div>
    </div>
     
    <div id="chatbox">
      <div class="envoi">
         <p>bonjour</p>
      </div>
      <div class="recu">
          <p>hello</p>
      </div>
    </div>

     
    <form name="message" action="">
        <input name="usermsg" type="text" id="usermsg" size="63" />
        <button id="submitmsg" name="submitmsg" type="submit" > <i class="fas fa-paper-plane"></i></button>
        
    </form>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src ="main.js"></script>
</body>
</html>